server:
  port: 8081
spring:
  application:
    name: 01 Spring Framework Intro
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:appdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  h2:
    console:
      enabled: true
    path: /h2-console